# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('min_humidity', models.SmallIntegerField()),
                ('max_humidity', models.SmallIntegerField()),
                ('sensor', models.CharField(choices=[('GPIO23', 'Sensor Probe 1'), ('GPIO24', 'Sensor Probe 2')], max_length=255)),
                ('sprinkler', models.CharField(choices=[('GPIO20', 'Sprinkler Pump 1'), ('GPIO21', 'Sprinkler Pump 2')], max_length=255)),
                ('enable_notifications', models.BooleanField(default=False)),
                ('notifications_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('current_humidity', models.SmallIntegerField(blank=True, null=True)),
                ('sprinkler_mode', models.CharField(choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Auto', max_length=255)),
                ('sprinkler_status', models.CharField(choices=[(1, 'ON'), (0, 'OFF')], default=0, max_length=255)),
            ],
        ),
    ]
