# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='enable_notifications',
            field=models.BooleanField(default=False, verbose_name='Send Notifications'),
        ),
        migrations.AlterField(
            model_name='station',
            name='max_humidity',
            field=models.SmallIntegerField(verbose_name='Max Humidity'),
        ),
        migrations.AlterField(
            model_name='station',
            name='min_humidity',
            field=models.SmallIntegerField(verbose_name='Min Humidity'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Station Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='notifications_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Notifications Email'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sensor',
            field=models.CharField(choices=[('GPIO23', 'Sensor Probe 1'), ('GPIO24', 'Sensor Probe 2')], max_length=255, verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sprinkler',
            field=models.CharField(choices=[('GPIO20', 'Sprinkler Pump 1'), ('GPIO21', 'Sprinkler Pump 2')], max_length=255, verbose_name='Sprinkler'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sprinkler_status',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'On')], default='Off', max_length=255),
        ),
    ]
