# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170225_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='enable_notifications',
            field=models.BooleanField(default=False, help_text='Smartfarm will send email reminders to this email if the sprinkler is in manual mode and humidity is outside the min - max range.', verbose_name='Send Notifications'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Station Name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sprinkler_status',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=255),
        ),
    ]
