# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20170226_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='current_humidity',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
