# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170326_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='sprinkler_status',
        ),
        migrations.AddField(
            model_name='station',
            name='sprinkler_is_on',
            field=models.BooleanField(default=False),
        ),
    ]
