# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170326_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='current_humidity',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
