# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170326_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='sprinkler_mode',
            field=models.CharField(blank=True, choices=[('Auto', 'Auto'), ('Manual', 'Manual')], default='Auto', max_length=255),
        ),
    ]
