# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20170326_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='station',
            name='weather_data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
