# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170415_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherforecast',
            old_name='time_of_request',
            new_name='time',
        ),
    ]
