# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20170415_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='blinker',
            field=models.CharField(choices=[('GPIO25', 'Blinker Pin 1'), ('GPIO26', 'Blinker Pin 2')], default='GPIO25', max_length=255, verbose_name='Blinker'),
            preserve_default=False,
        ),
    ]
