# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_station_blinker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='blinker',
            field=models.CharField(choices=[(b'24', b'Blinker Pin 1')], max_length=255, verbose_name=b'Blinker'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sensor',
            field=models.CharField(choices=[(b'17', b'Sensor Probe 1')], max_length=255, verbose_name=b'Sensor'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sprinkler',
            field=models.CharField(choices=[(b'23', b'Sprinkler Pump 1')], max_length=255, verbose_name=b'Sprinkler'),
        ),
    ]
