# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20170418_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='blinker',
            field=models.CharField(choices=[(b'5', b'Blinker Pin 1')], max_length=255, verbose_name=b'Blinker'),
        ),
        migrations.AlterField(
            model_name='station',
            name='sprinkler',
            field=models.CharField(choices=[(b'6', b'Sprinkler Pump 1')], max_length=255, verbose_name=b'Sprinkler'),
        ),
    ]
